name: gp_2_2_2_2_2dim
benchmark: gp_2_2_2_2_2dim
num_iters: 100
num_init: 5
parameters: null
bounds: [[0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1]]
prior_location: [3.1415278, 2.275]
noise_std: 0.5
range: 308
model_parameters:
  lengthscale: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
  outputscale: [1]
  active_groups: [0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5]